name: Integration Tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]

jobs:
  get-discovery-schemas:
    name: Get Discovery Schemas
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Matrix
        id: set-matrix
        run: echo "::set-output name=matrix::$(ls schemas/discovery/*.json | jq -R -s -c 'split("\n")[:-1]')"

  validation:
    name: Validate Discovery Schemas
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: get-discovery-schemas
    strategy:
      matrix:
        schemas: ${{ fromJson(needs.get-discovery-schemas.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/schemas/validation/requirements.txt

      - name: Validate Discovery Schemas
        run: python3 tools/schemas/validation/main.py ${{ matrix.schemas }} schemas/definitions/discovery.schema.json
