name: Terraform Security Scan
on:
  pull_request:
jobs:
  build:
    name: Run Trivy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in Repo mode
        uses: aquasecurity/trivy-action@0.16.1
        with:
          format: 'sarif'
          exit-code: '1'
          hide-progress: false
          ignore-unfixed: true
          output: 'trivy-results.sarif'
          scan-type: 'fs'
          scanners: "vuln,secret"
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
