name: Analysis

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]
  schedule:
    - cron: "0 11 * * 0" # 3 AM PST = 12 PM UDT, runs sundays
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # tests:
  #   name: Tests
  #   if: ${{ ! github.event.pull_request.draft }}
  #   runs-on: ubuntu-22.04
  #   timeout-minutes: 5
  #   # services:
  #   #   postgres:
  #   #     image: postgres
  #   #     env:
  #   #       POSTGRES_PASSWORD: postgres
  #   #     options: >-
  #   #       --health-cmd pg_isready
  #   #       --health-interval 10s
  #   #       --health-timeout 5s
  #   #       --health-retries 5
  #   #     ports:
  #   #       - 5432:5432
  #   steps:
  #     - uses: bcgov-nr/action-test-and-analyse@v1.2.1
  #       with:
  #         commands: |
  #           # npm ci
  #           # npm run test:cov
  #           echo "Testing - coming soon!"
  #         dir: ${{ matrix.dir }}
  #         node_version: "20"
  #         sonar_args: >
  #           -Dsonar.exclusions=**/coverage/**,**/node_modules/**,**/*spec.ts
  #           -Dsonar.organization=bcgov-sonarcloud
  #           -Dsonar.projectKey=nr-data-hub
  #           -Dsonar.sources=src
  #           -Dsonar.tests.inclusions=**/*spec.ts
  #           -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
  #         sonar_token: ${{ secrets.SONAR_TOKEN_DATA_HUB }}
  #         triggers: ('${{ matrix.dir }}/')

  codeql:
    name: CodeQL Scan
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"

  # https://github.com/marketplace/actions/aqua-security-trivy
  trivy:
    name: Trivy Scan
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.19.0
        with:
          format: "sarif"
          hide-progress: false
          ignore-unfixed: true
          output: "trivy-results.sarif"
          scan-type: "fs"
          scanners: "vuln,secret"
          severity: "CRITICAL,HIGH"

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
